### ISSUE TITLE
Make comparison section for clients

### ISSUE THREAD

**Issue by stubailo** [apollostack/core-docs#110]
Compare apollo client to relay, lokka, and maybe cashay

**Comment by helfer** [comment]
I think at the moment it doesn't make sense to compare to anything other than Relay.

**Comment by stubailo** [comment]
Yeah that makes sense to me!

**Comment by gonsfx** [comment]
Why is that? Cashay and Lokka try to solve a lot of problems that relay and apollo-client also try to solve.

**Comment by stubailo** [comment]
I guess I'm not really sure what the criteria are for comparing to something. I suspect the overwhelming majority of people will be mostly interested in Relay, but we'll see what the comparisons to other stuff look like as well. Perhaps we can ask people to contribute to those?

**Comment by tonyxiao** [comment]
Did this end up becoming a thing?

**Comment by stubailo** [comment]
I think we are still going to do it. We are working up to a more focused "launch" so we are prioritizing tasks in terms of risk.

There's a basic start here:

http://dev.apollodata.com/react/#comparison

It's up to me to make it more detailed, but you can help as well!

**Comment by lirbank** [comment]
Here is another comparison http://www.codazen.com/choosing-graphql-client-apollo-vs-relay/

**Comment by stubailo** [comment]
I think with the info on the [new landing page](http://dev-home.apollodata.com/) and that docs section, we're pretty good on this front.
