### ISSUE TITLE
Meteor Impersonate

### ISSUE THREAD

**Issue by ickyrr** [apollostack/core-docs#204]
Hello, I've just integrated meteor and apollo server into one project. I can receive the context which is `{userId: "some-id"}` in my resolver. I am also using [gwendall:impersonate](https://atmospherejs.com/gwendall/impersonate).

I have 2 user roles, admin and client. My problem is when I do impersonate, the userId on the context won' change. Is there any workaround for this? Thanks for the help!

**Comment by helfer** [comment]
Hi @ickyrr, I think this doesn't have anything to do with the docs here and would be a better question for the Meteor forums. You should ask it there.
