### ISSUE TITLE
Missing logo and brand images in server docs

### ISSUE THREAD

**Issue by HriBB** [apollostack/core-docs#207]
Just wanted to let you know that there are missing logo and brand images in server docs.

![apollo](https://cloud.githubusercontent.com/assets/4412324/18731055/e7051942-8059-11e6-9899-fbbe98fcb6bd.png)

**Comment by HriBB** [comment]
Now it works. Closing.

**Comment by stubailo** [comment]
Yeah might have been a cache thing
