### ISSUE TITLE
Logging from middleware

### ISSUE THREAD

**Issue by richburdon** [apollostack/core-docs#224]
I'm experimenting with middleware and want to log the response, but the "body" param of the request is a ReadableStream. Without creating a custom network interface, can I get a callback once the response has been parsed?

```
networkInterface.useAfter([{
  applyAfterware({ response }, next) {
    logging.log(response.body);
  }
}]);
```

**Comment by stubailo** [comment]
I think you need to use clone for this: https://developer.mozilla.org/en-US/docs/Web/API/Response/clone

So you can do `response.clone().json()` to get the JSON result, while not disrupting middlewares further down the chain.

**Comment by richburdon** [comment]
Thanks @stubailo, that works.

Is there a simpler (more standard way to enable GraphQL logging -- both client, and graphqlExpress server?)

**Comment by stubailo** [comment]
Not right now, but if you have any ideas I'd love to hear them!

**Comment by richburdon** [comment]
@stubailo, my current implementation below using expressjs router middleware.

If you think it's useful I send a PR?

```
const graphqlLogger = () => {
  return (req, res, next) => {
    let { operationName, query, variables } = req.body;

    let input = {
      operationName,
      query: query.replace(/\s*\n\s*/g, ' '),
      variables
    };

    console.log('>>> REQ: [%s]', JSON.stringify(input, 0, 2));

    let original = res.end;
    res.end = (json) => {
      console.log(typeof json);
      console.log('<<< RES: [%s]', JSON.stringify(JSON.parse(json), 0, 2));
      return original.call(res, json);
    };

    next();
  }
};

const router = express.Router();
router.use('/graphql', graphqlLogger());
app.use('/', router);
```

**Comment by richburdon** [comment]
Sorry, I spoke too soon:

The solution above works with graphqlHTTP (express-graphq), but I get the following error with graphqlExpress. I'll have to research it.

(node:8516) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token u in JSON at position 0

**Comment by stubailo** [comment]
This docs repo is only about client-side logging, which would be using `apollo-client` middleware. If we're talking about server logging it's probably best to do that somewhere else.

**Comment by richburdon** [comment]
Yes, of course, makes sense (still getting orientated).

To close the thread, I've copies my expressjs middleware solution below (cross-posted here: https://github.com/graphql/express-graphql/issues/107)

```
app.use('/graphql'., graphqlLogger());

export const graphqlLogger = () => {
  return (req, res, next) => {
      let { operationName, query, variables } = req.body;

      query = query.replace(/\s*\n\s*/g, ' ');
      console.log('### REQ ### %s %s', query, stringify(variables));

      // Monkey patch.
      let originalWrite = res.write;
      res.write = (data) => {
        switch (res.statusCode) {
          case 200:
            console.log('### RES ### %s', data);
            break;

          default:
            console.error(data);
        }

        return originalWrite.call(res, data);
      };

    next();
  }
};

```
